### ISSUE TITLE
Error handler attached too late?

### ISSUE THREAD

**Issue by RubenVerborgh** [rubensworks/arrayify-stream.js#3]
The error handler is only attached in the `new Promise` callback, which might cause us to miss errors thrown before that:
https://github.com/rubensworks/arrayify-stream.js/blob/f092c17711f3adc817de25eea04e232990d744b2/index.js#L7

Should it be moved to the first line of the exported function?
See https://github.com/solid/community-server/pull/462#issuecomment-756649497

**Comment by RubenVerborgh** [comment]
…and should also detach when done?

**Comment by rubensworks** [comment]
> Should it be moved to the first line of the exported function?

So moving it outside the promise?
Problem is that we don't have a reference to `reject` yet.

We can of course re-bind to `reject` once it becomes defined, but there might be a period during which errors have no place to go.
Can't think of any better way than just letting Node take care of this, by considering it an unhandled error.

A hacky way would be to re-emit the error behind a `setImmediate`, in the hope that `reject` has already been defined by then.

> …and should also detach when done?

Yes, definitely.

**Comment by RubenVerborgh** [comment]
>  Can't think of any better way than just letting Node take care of this, by considering it an unhandled error.

I can: just save whatever error you catch in the meantime, knowing that your promise callback _will_ be called next in any case. Then you just do `if (caughtError) throw caughtError`.

**Comment by rubensworks** [comment]
Right, of course 🤦
